# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-06 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('received', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Awaiting Authorisation', b'Awaiting Authorisation'), (b'Completed', b'Completed'), (b'Declined', b'Declined'), (b'Reversed', b'Reversed')], default=b'Pending', max_length=100)),
                ('send_notification', models.BooleanField(default=True)),
                ('hold_expire', models.DateTimeField(auto_now_add=True, null=True)),
                ('on_hold', models.BooleanField(default=False)),
                ('fee', models.FloatField(default=0)),
                ('calculate_total', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('stock', models.CharField(default=0, max_length=50)),
                ('is_unlimited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('support_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('airtime_transfer_limit', models.IntegerField(default=1000)),
                ('daily_limit', models.FloatField(blank=True, default=200, null=True)),
                ('airtime_transfer_instructions', models.TextField(blank=True, max_length=500, null=True)),
                ('deposit_denominations', models.CharField(blank=True, default=b'5,10', max_length=200, null=True)),
                ('deposit_fee', models.FloatField(blank=True, default=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribed', models.DateTimeField(auto_now=True)),
                ('is_unsubscribed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('stamp_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Cancelled', b'Cancelled'), (b'Completed', b'Completed')], default=b'Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=100)),
                ('stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(blank=True, max_length=500, null=True)),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('moderated', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('actual_balance', models.FloatField(blank=True, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=20, null=True)),
                ('sim_no', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(b'New', b'New'), (b'Deactivated', b'Deactivated'), (b'Receiving', b'Receiving'), (b'Paused', b'Paused'), (b'Dispatch', b'Dispatch'), (b'Circulating', b'Circulating')], default=b'New', max_length=100)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Network')),
            ],
        ),
        migrations.CreateModel(
            name='SmsInbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=150, null=True)),
                ('sender', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=150, null=True)),
                ('source_id', models.CharField(blank=True, max_length=150, null=True)),
                ('network_id', models.CharField(blank=True, max_length=150, null=True)),
                ('received_time', models.DateTimeField(auto_now=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SmsOutBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('status_string', models.CharField(blank=True, max_length=50, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_dispatched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(choices=[(b'Credit', b'Credit'), (b'Debit', b'Debit')], max_length=100)),
                ('fee', models.FloatField(default=0)),
                ('fee_type', models.CharField(choices=[(b'Percent', b'Percent'), (b'Amount', b'Amount')], default=b'Amount', max_length=50)),
                ('include_in_fees', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=150, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=50, null=True)),
                ('identification_no', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_country', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.FloatField(default=0)),
                ('from_quasar', models.BooleanField(default=False)),
                ('thisisme_verified', models.BooleanField(default=False)),
                ('device_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('identifier', models.ManyToManyField(to='website.UniqueIdentifier')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='smsoutbound',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
        migrations.AddField(
            model_name='referral',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
        migrations.AddField(
            model_name='prepaidlead',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
        migrations.AddField(
            model_name='prepaidlead',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='website.UserProfile'),
        ),
        migrations.AddField(
            model_name='prepaidlead',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TransactionType'),
        ),
        migrations.AddField(
            model_name='marketproduct',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
        migrations.AddField(
            model_name='fundstransaction',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Network'),
        ),
        migrations.AddField(
            model_name='fundstransaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
        migrations.AddField(
            model_name='fundstransaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TransactionType'),
        ),
    ]
