# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0002_auto_20170104_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtimedepositlead',
            name='sim_card',
        ),
        migrations.AddField(
            model_name='airtimedepositlead',
            name='sim_card',
            field=models.ManyToManyField(blank=True, related_name='airtime_deposit_lead_sim_card', to='website.SimCard'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 7, 15, 48, 46, 259548)),
        ),
    ]
