# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170107_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimedepositlead',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Accepted', b'Accepted'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 7, 18, 54, 58, 163197)),
        ),
    ]
