# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('debit', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('identifiers', models.ManyToManyField(to='website.UniqueIdentifier')),
            ],
        ),
        migrations.AddField(
            model_name='pocket',
            name='transactions',
            field=models.ManyToManyField(to='website.Transaction'),
        ),
    ]
