# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170107_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimedepositlead',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='airtime_deposit_transactions', to='website.Transaction'),
        ),
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='identifiers',
            field=models.ManyToManyField(blank=True, related_name='airtime_deposit_identifiers', to='website.UniqueIdentifier'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 7, 19, 30, 43, 766119)),
        ),
    ]
