# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170104_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
