# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170107_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 7, 21, 19, 9, 910747)),
        ),
    ]
