# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_userprofile_pockets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='transactions',
            field=models.ManyToManyField(null=True, to='website.Transaction'),
        ),
    ]
