# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170107_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='d_o_b',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 10, 7, 49, 5, 950295)),
        ),
    ]
