# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170105_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='identifiers',
            field=models.ManyToManyField(blank=True, null=True, to='website.UniqueIdentifier'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='transactions',
            field=models.ManyToManyField(blank=True, null=True, to='website.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='identifiers',
            field=models.ManyToManyField(blank=True, null=True, to='website.UniqueIdentifier'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.ManyToManyField(blank=True, null=True, to='website.UniqueIdentifier'),
        ),
    ]
