# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170110_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 10, 7, 49, 40, 914027)),
        ),
    ]
