# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170110_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='d_o_b',
            field=models.DateField(blank=True, null=True),
        ),
    ]
