# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170110_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
