# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170105_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 5, 10, 27, 58, 67162)),
        ),
    ]
