# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170110_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simcard',
            old_name='balance',
            new_name='balance_day',
        ),
        migrations.RenameField(
            model_name='simcard',
            old_name='actual_balance',
            new_name='balance_month',
        ),
    ]
