# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170105_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='double_entry',
            field=models.ManyToManyField(blank=True, related_name='transactions_double_entry', to='website.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 5, 10, 53, 2, 801524)),
        ),
    ]
