# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170110_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='balance_month',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
