# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170105_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 5, 11, 13, 6, 975275)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='double_entry',
            field=models.ManyToManyField(blank=True, related_name='transactions_double_entry', to='website.Pocket'),
        ),
    ]
