# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170110_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
