# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170105_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='double_entry',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 5, 13, 21, 31, 700525)),
        ),
    ]
