# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_transaction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdepositlead',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Accepted', b'Accepted'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='bankpaymentlead',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Accepted', b'Accepted'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Accepted', b'Accepted'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100),
        ),
    ]
