# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170105_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 5, 22, 43, 13, 424576)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_pocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_default_pocket', to='website.Pocket'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pockets',
            field=models.ManyToManyField(blank=True, related_name='user_profile_pocket', to='website.Pocket'),
        ),
    ]
