# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170111_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdepositlead',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankpaymentlead',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
