# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170105_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=150, null=True)),
                ('account_no', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifiers', models.ManyToManyField(blank=True, to='website.UniqueIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='CrowdcoinPaymentLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifiers', models.ManyToManyField(blank=True, to='website.UniqueIdentifier')),
            ],
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_pocket', to='website.Pocket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 6, 14, 33, 15, 927968)),
        ),
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='pocket_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_payment_lead_pocket_from', to='website.Pocket'),
        ),
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='pocket_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_payment_lead_pocket_to', to='website.Pocket'),
        ),
        migrations.AddField(
            model_name='bankpaymentlead',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment_lead_pocket', to='website.Pocket'),
        ),
    ]
