# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20170106_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirtimePaymentLead',
            new_name='AirtimeDepositLead',
        ),
        migrations.AlterField(
            model_name='crowdcoinpaymentlead',
            name='pocket_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowdcoin_payment_lead_pocket_from', to='website.Pocket'),
        ),
        migrations.AlterField(
            model_name='crowdcoinpaymentlead',
            name='pocket_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowdcoin_payment_lead_pocket_to', to='website.Pocket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 6, 15, 1, 1, 166486)),
        ),
    ]
