# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20170106_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDepositLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifiers', models.ManyToManyField(blank=True, to='website.UniqueIdentifier')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposit_lead_pocket', to='website.Pocket')),
            ],
        ),
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_deposit_lead_pocket', to='website.Pocket'),
        ),
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='sim_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_deposit_lead_sim_card', to='website.SimCard'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 6, 15, 7, 22, 18394)),
        ),
    ]
