# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20170106_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 6, 16, 52, 2, 404577)),
        ),
    ]
