# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20170106_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 1, 6, 18, 56, 44, 256)),
        ),
        migrations.AlterField(
            model_name='uniqueidentifier',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
