# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-14 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20170111_1556'),
        ('website', '0027_auto_20170106_1857'),
    ]

    operations = [
    ]
