# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='pocket',
            name='tag',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
