# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20170117_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
