# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-18 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_pocket_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='created',
        ),
        migrations.AddField(
            model_name='pocket',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 18, 14, 28, 10, 27370, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
