# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-18 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20170118_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='updated',
        ),
        migrations.AddField(
            model_name='pocket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 18, 14, 31, 40, 771182, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
