# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_crowdcoinpaymentlead_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPaymentLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(blank=True, max_length=150, null=True)),
                ('security_pin', models.CharField(blank=True, max_length=150, null=True)),
                ('days_valid', models.IntegerField(blank=True, default=7, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('currency', models.CharField(blank=True, default=b'ZAR', max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Awaiting Collection', b'Awaiting Collection'), (b'Collected', b'Collected'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('pocket_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_payment_lead_pocket_from', to='website.Pocket')),
                ('pocket_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_payment_lead_pocket_to', to='website.Pocket')),
            ],
        ),
    ]
