# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_voucherpaymentlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='pocket_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_payment_lead_pocket_from', to='website.Pocket'),
        ),
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='pocket_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_payment_lead_pocket_to', to='website.Pocket'),
        ),
    ]
