# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20170331_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='msisdn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voucherpaymentlead',
            name='recipient_msisdn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='voucherpaymentlead',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='voucherpaymentlead',
            name='sender_msisdn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='voucherpaymentlead',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
