# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20170331_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='status',
            field=models.CharField(choices=[(b'Awaiting Collection', b'Awaiting Collection'), (b'Collected', b'Collected'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Awaiting Collection', max_length=100),
        ),
    ]
