# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20170428_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='referred',
        ),
    ]
