# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_claimedpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedpromotion',
            name='datetime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
