# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_claimedpromotion_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimedpromotion',
            name='referrer',
        ),
        migrations.AddField(
            model_name='promotion',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_pocket', to='website.Pocket'),
        ),
    ]
