# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20170429_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='status',
            field=models.CharField(choices=[(b'Awaiting Collection', b'Awaiting Collection'), (b'Collected', b'Collected'), (b'Pending', b'Pending'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100),
        ),
    ]
