# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_auto_20170819_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='cancel_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
