# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_userprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='item_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='item_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='notify_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='return_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
