# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20170820_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdcoinpaymentlead',
            name='airtime_deposit_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_deposit_lead', to='website.AirtimeDepositLead'),
        ),
    ]
