# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_crowdcoinpaymentlead_airtime_deposit_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='pocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_deposit_lead_pocket', to='website.Pocket'),
        ),
    ]
