# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_auto_20170820_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeDepositTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('expiary_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='airtime_deposit_lead_transactions', to='website.Transaction'),
        ),
        migrations.AddField(
            model_name='airtimedepositlead',
            name='airtime_deposit_transactions',
            field=models.ManyToManyField(blank=True, related_name='airtime_deposit_transactions', to='website.AirtimeDepositTransaction'),
        ),
    ]
