# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_auto_20170821_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimedeposittransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airtimedeposittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
