# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_auto_20170821_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimedeposittransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
