# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_auto_20170821_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimedeposittransaction',
            name='reference',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
