# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_auto_20170821_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
