# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_auto_20170822_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='online_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
