# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_simcard_online_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='callback_method',
            field=models.CharField(default=b'POST', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='email_notification',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='callback_url',
            field=models.URLField(blank=True, default=b'http://', null=True),
        ),
    ]
