# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_auto_20170913_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='display_on_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='subscription',
            field=models.CharField(choices=[(b'Trial', b'Trial'), (b'Premium', b'Premium'), (b'Enterprise', b'Enterprise')], default=b'Trial', max_length=100),
        ),
    ]
