# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_auto_20170918_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='voucher_recieving_fee',
            field=models.CharField(blank=True, default=b'0', max_length=100),
        ),
        migrations.AddField(
            model_name='pocket',
            name='voucher_sending_fee',
            field=models.CharField(blank=True, default=b'15%', max_length=100),
        ),
    ]
