# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_auto_20180125_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocket',
            old_name='voucher_recieving_fee',
            new_name='voucher_receiving_fee',
        ),
    ]
