# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_auto_20180129_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='voucher_receiving_fee',
            field=models.CharField(blank=True, default=b'0%', max_length=100),
        ),
    ]
