# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_auto_20180129_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpaymentlead',
            name='provider',
            field=models.CharField(blank=True, default=b'Crowdcoin', max_length=150),
        ),
    ]
